### PR TITLE
Added binary algorithms

### PR DESCRIPTION
**Pull request by IanDoarn**
#Binary 
per #45 I've implemented conversions between binary base's 2, 10, and 16 as well as ASCII

- binary
  - added binary conversions:
    - ascii_to_base2.py
    - ascii_to_base16.py
    - base2_to_ascii.py
    - base2_to_base10.py
    - base2_to_base16.py
    - base10_to_base2.py
    - base10_to_base16.py
    - base16_to_ascii.py
    - base16_to_base2.py
    - base16_to_base10.py

### CODE REVIEW

**Comment by Tjstretchalot** [comment]
I wonder if you could complete it with a base n to m conversion, where n, m, and the conversion table are supplied? https://math.stackexchange.com/questions/48968/how-to-change-from-base-n-to-m

If you finish that up with an option to pass in the keyset (ie 1,2,3,4,5,6,7,8,9,0,A,B,C,D,E,F for base 16) then you could have a test to see it works the same as the ones you have here.

Might be neat!

**Comment by OmkarPathak** [comment]
I agree with @Tjstretchalot. I would be nicer to have a function for base n to m conversion. Also, I was thinking that instead of making separate files for each of these conversions, wouldn't it be feasible to place them into a single file?

**Comment by IanDoarn** [comment]
@OmkarPathak How about place thing in files based on base? like base2.py, base 16.py, ect.?

**Comment by OmkarPathak** [comment]
@IanDoarn  base2.py, base 16.py would also do

**Comment by IanDoarn** [comment]
@Tjstretchalot @OmkarPathak I'll work on these suggestions and update this pull!

**Comment by IanDoarn** [comment]
@Tjstretchalot @OmkarPathak Ill work with the bases 2,10,16 and ascii for now and add high / less common bases later such as 8, 256, 1024 ect.

**Comment by IanDoarn** [comment]
@OmkarPathak Ready to merge for now

**Pull request merged**
