### PR TITLE
Abstract base class for DS

### PR DESCRIPTION
**Pull request by abramovd**
- Abstract base class for Data structures. Currently used only for `data_structures.stack`.
- Mixin for data structures unittests to check that data structure implements required methods (might be useful for new developers)

One TODO:
I don't fully understand either `time_complexities` method is required or not. I can't see it in a majority of implemented data structures. I added it to base class, but only with `pass` in its body for now.

If such refactoring approach is ok, I can do the same for other DS classes.

### CODE REVIEW

**Comment by OmkarPathak** [comment]
@IanDoarn @Tjstretchalot  what do you think, should we use this method for all data structures? I really like the way. Just wanted a second thought from someone.

**Comment by Tjstretchalot** [comment]
I think it belongs in the documentation, personally. It's pretty difficult to find for some algorithms

**Comment by OmkarPathak** [comment]
@Tjstretchalot so should we incorporate the changes or not?

**Comment by Tjstretchalot** [comment]
I like the base class, I don't like the DS_Class variable and changing the base class for the tests. I'm not sure I see the point in that exactly, since you can accomplish the same thing without using DS_Class and the interface mixin is a lot harder to read

**Comment by OmkarPathak** [comment]
Okay. So sadly @abramovd we have to drop this idea. But thanks for your contribution anyway :+1:

**Pull request closed without merging**
